(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ada-build-check-cmd "gprbuild -p -P${gpr_file} -c -u -f ${full_current}")
 '(ada-build-make-cmd "gprbuild -p -P${gpr_file}")
 '(ada-case-exception-file '("~/.emacs_case_exceptions"))
 '(ada-case-strict nil)
 '(ada-fill-comment-postfix "  --")
 '(ada-fill-comment-prefix #("--  " 0 2 (syntax-table (11))))
 '(ada-indent-comment-gnat nil)
 '(ada-indent-label 0)
 '(ada-language-version 'ada2012)
 '(ada-popup-key '[C-down-mouse-3])
 '(ada-prj-default-check-cmd
   "gprbuild -c -u -f -gnatc -p -P ${gpr_file} ${full_current}")
 '(ada-prj-default-make-cmd "gprbuild -p -P ${gpr_file}")
 '(ada-prj-file-ext-extra '("gpr"))
 '(ada-process-parse-exec-opts
   '("--recover-log" "/Users/simon/Developer/ada-mode/recover.log"))
 '(ada-skel-initial-string "")
 '(ada-ts-mode-indent-backend 'lsp)
 '(before-save-hook nil)
 '(c-basic-offset 2)
 '(canlock-password "574cc640a3673e23b6401102b43514ca2f7cecb6")
 '(confirm-kill-emacs 'yes-or-no-p)
 '(custom-file "~/.emacs-custom.el")
 '(default-frame-alist
   '((menu-bar-lines . 1)
     (right-fringe)
     (left-fringe)
     (top . 0)
     (left . 0)
     (width . 80)
     (height . 52)))
 '(delete-selection-mode t)
 '(delete-trailing-lines nil)
 '(enscript-borders t)
 '(enscript-color nil)
 '(enscript-columns 2)
 '(enscript-landscape t)
 '(enscript-margins "54:::")
 '(enscript-output "")
 '(enscript-ps-level 1)
 '(global-font-lock-mode t nil (font-lock))
 '(gnus-large-newsgroup 600)
 '(gnus-message-archive-group nil)
 '(gnus-select-method '(nntp "news.eternal-september.org"))
 '(gpr-skel-initial-string "")
 '(imenu-auto-rescan t)
 '(indent-tabs-mode nil)
 '(initial-frame-alist '((top . 0) (left . -1) (width . 80) (height . 52)))
 '(javascript-indent-level 2)
 '(markdown-command "perl ~/bin/Markdown.pl")
 '(mouse-buffer-menu-mode-mult 1)
 '(mouse-drag-copy-region t)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount '(2 ((shift) . 1) ((control))))
 '(next-line-add-newlines nil)
 '(ns-alternate-modifier 'none)
 '(ns-command-modifier 'meta)
 '(ns-pop-up-frames nil)
 '(package-archives
   '(("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "https://melpa.org/packages/")))
 '(package-selected-packages
   '(gpr-yasnippets eglot company yasnippet gpr-ts-mode lsp-mode ada-ts-mode gpr-query gpr-mode ada-mode markdown-preview-mode other-frame-window ada-ref-man))
 '(python-check-command "python -m flake8")
 '(scroll-bar-mode 'right)
 '(send-mail-function 'mailclient-send-it)
 '(sgml-basic-offset 0)
 '(tex-font-script-display '(-0.0 0.0))
 '(tex-suscript-height-ratio 1.0)
 '(tool-bar-mode nil nil (tool-bar))
 '(use-file-dialog nil)
 '(user-mail-address "simon@pushface.org")
 '(vc-git-diff-switches '("-b"))
 '(vc-path nil)
 '(verilog-auto-delete-trailing-whitespace t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "White" :foreground "Black" :inverse-video nil :box nil :strike-through nil :extend nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Inconsolata")))))
